import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ['latin'], // bisa tambahkan 'latin-ext' atau 'cyrillic' sesuai kebutuhan
  display: 'swap',     // agar teks tetap muncul walau font belum sepenuhnya dimuat
  variable: '--font-inter', // untuk penggunaan dengan className
})
export const metadata: Metadata = {
  title: "Ahza LMS",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster/>
          </ThemeProvider>
      </body>
    </html>
  );
}
